### ISSUE TITLE
got errors for  CFG_sx1272_radio/CFG_sx1276_radio

### ISSUE THREAD

**Issue by luisgcu** [beegee-tokyo/SX1262-SC-GW#1]
Looks like this is nice project. 
I Pretend to use ESP32 with RFM95 
 But I got lot of  errors while compiling for  CFG_sx1272_radio/CFG_sx1276_radio 
src\main.cpp:459:10: error: 'pins' was not declared in this scope
src\defines.h:400:32: error: 'gway_failed' was not declared in this scope

**Comment by beegee-tokyo** [comment]
This is a fork of [ESP-1ch-Gateway](https://github.com/things4u/ESP-1ch-Gateway) which supports only Semtech SX126x chips. If you want to use Semtech SX127x chips please use the original application.
