### ISSUE TITLE
Question : How to use this repo for Arduino Platform ? 

### ISSUE THREAD

**Issue by ankitghevariya** [beegee-tokyo/SX1262-SC-GW#2]
Hello,

I have gone through your Repo. It seems you have forked it from https://github.com/things4u/ESP-1ch-Gateway.

I was just finding .ino file to upload code into ESP32 using Arduino build. Could you please guide me with the same ?

Thank you
Anks

**Comment by beegee-tokyo** [comment]
Hi,

Create a folder named **`SX1262-SC-GW`**
Copy all files from the **`src`** folder into your new folder.
Rename **`main.cpp`** to **`SX1262-SC-GW.ino`**

You will need all the libraries in the **`lib`** folder installed in ArduinoIDE.

Then you should be able to compile it.
